# Generated by Django 2.2.13 on 2021-08-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Webshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='owner',
        ),
    ]
