# Generated by Django 2.2.13 on 2021-08-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
