# Generated by Django 2.2.13 on 2021-08-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webshop', '0002_auto_20210827_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='is_ordered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
