# Generated by Django 2.2.13 on 2021-08-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webshop', '0002_auto_20210811_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
