# Generated by Django 2.2.13 on 2021-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webshop', '0002_remove_orderitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageurl',
            field=models.URLField(),
        ),
    ]
